Server client
MaelTeyssedre/R-TYPE pull request #195
Opened 2021-11-28 19:38 UTC by Alban-Bodenes

2021-11-28 20:11 UTC, MaelTeyssedre requested changes

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Commons/INetwork/ITCPServer.hpp
> +            // virtual std::shared_ptr<Buffer> getBuffer() =  0;
to delete

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/RtypeClient.cpp
> +    // struct components::currentScene_s scene = {constants::SCENE::LOADING_MENU, false};
to delete

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/RtypeClient.cpp
> +}
end of line

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/Systems.hpp
> +*/
to delete

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateDirection/UpdateDirection.cpp
> +*/
to delete

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateDirection/UpdateDirection.cpp
> +// TODO rajouter le composant controllable
done

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateDirection/UpdateDirection.cpp
> +}
end of line

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateDirection/UpdateDirection.hpp
> +*/
to delete

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateGraph/UpdateGraph.hpp
> +            private: // * fill _setupScene map
delete comment

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateGraph/UpdateGraph.hpp
> +            private: // * fill _execScene map
delete comment

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateGraph/UpdateGraph.hpp
> +            private: // * fill _deleteScene map
delete comment

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateNetwork/UpdateNetwork.cpp
> +}
end of line

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdatePosition/UpdatePosition.cpp
> +*/
to delete

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdatePosition/UpdatePosition.hpp
> +
to delete

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateTime/UpdateTime.cpp
> +    // }
to delete

2021-11-28 20:11 UTC, MaelTeyssedre commented on Sources/Client/Systems/UpdateTime/UpdateTime.cpp
> +    }
useless brackets

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Network/NetworkManager/NetworkManager.hpp
>  #endif /* !NETWORKMANAGER_HPP_ */
Add line

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Network/Packet/Packet.cpp
>  }
Add line

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Network/Packet/Packet.hpp
>  #endif /* !PACKET_HPP_ */
Add line

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Network/TCP/tcpServer.cpp
>  }
Add line

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Network/UDP/udpSocket.cpp
> +    // std::cout << "send data via udp" << std::endl;
Comment

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Network/UDP/udpSocket.cpp
> +    // std::cout << _data << std::endl;
Comment

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Network/User/tcpUser.cpp
> +}
Add line

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/PacketManager/PacketManager.cpp
> +}
Add line

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Systems/UpdateNetwork.cpp
> +            network.value().request17.push_back(std::vector<uint8_t>());
Comment

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Systems/UpdateTime/UpdateTime.cpp
> +    // }
Comment

2021-11-28 20:12 UTC, Alban-Bodenes commented on Sources/Server/Systems/UpdateTime/UpdateTime.hpp
> +    //#include "Zipper.hpp"
Comment

2021-11-28 20:34 UTC, Jsavang requested changes

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/GraphicalLib.hpp
> +                std::map<size_t, std::shared_ptr<Sound>> _soundMap; // There is an id Jules
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/GraphicalLib.hpp
> +                std::map<size_t, std::shared_ptr<Music>> _musicMap; // There is an id Jules
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/IGraphicalLib.hpp
> +                virtual void draw(size_t id) = 0; // for sprite
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/IGraphicalLib.hpp
> +                virtual void print(size_t id) = 0; // for text
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/IGraphicalLib.hpp
> +                virtual void start(size_t id) = 0; // for sound
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/IGraphicalLib.hpp
> +                virtual void play(size_t id) = 0; // for music
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/IGraphicalLib.hpp
> +                virtual void stop(size_t id) = 0; //for music
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/IGraphicalLib.hpp
> +                virtual void pause(size_t id) = 0; //for music
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/NetworkManager/NetworkManager.hpp
> +                 * \fn explicit NetworkManager()
to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/NetworkManager/NetworkManager.hpp
> +                 *
wrong prototype in doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/NetworkManager/NetworkManager.hpp
> +                 *
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/NetworkManager/NetworkManager.hpp
> +                 *
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/Packet/cPacket.cpp
>  }
miss a newline

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/Packet/cPacket.hpp
> +                *
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/TCP/cTCPClient.hpp
> +                 * \brief Destroy the TCPClient object
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/TCP/cTCPClient.hpp
> +                 * \fn std::shared_ptr<Buffer> getData()
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/UDP/cUDPSocket.hpp
> +               * \brief ctor udp client
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/UDP/cUDPSocket.hpp
> +               * \brief receive data from network
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/RtypeClient.cpp
> +    // struct components::currentScene_s scene = {constants::SCENE::LOADING_MENU, false};
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/RtypeClient.cpp
>   * Systems
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateDirection/UpdateDirection.cpp
> +** File description:
epitech header to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateDirection/UpdateDirection.hpp
> +** R-TYPE
epitech header to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateGraph/UpdateGraph.hpp
> +            private: // * fill _setupScene map
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateGraph/UpdateGraph.hpp
> +            private: // * fill _execScene map
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateGraph/UpdateGraph.hpp
> +            private: // * fill _deleteScene map
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateNetwork/UpdateNetwork.cpp
> +}
newline to add

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdatePosition/UpdatePosition.cpp
> +** R-TYPE
epitech header to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdatePosition/UpdatePosition.hpp
> +** R-TYPE
epitech header to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateTime/UpdateTime.cpp
> +    // for (auto &&[time] : Zipper(times)) {
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/Systems.hpp
> +** R-TYPE
header

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateDirection/UpdateDirection.cpp
> +** EPITECH PROJECT, 2021
header

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateDirection/UpdateDirection.hpp
> +** R-TYPE
header

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateGraph/UpdateGraph.hpp
> +#ifndef UPDATEGRAPH_HPP_
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateNetwork/UpdateNetwork.cpp
> +}
newline to add

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdatePosition/UpdatePosition.cpp
> +** R-TYPE
header

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdatePosition/UpdatePosition.hpp
> +** R-TYPE
header

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Systems/UpdateTime/UpdateTime.cpp
> +    // for (auto &&[time] : Zipper(times)) {
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Commons/INetwork/IPacket.hpp
>           * \return data deserialised
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Commons/INetwork/ITCPServer.hpp
> +            //  *
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Server/Component/HealPoint.hpp
>           *
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Server/Component/Velocity.hpp
> -         * \struct velocity_s
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Server/Component/Weapon.hpp
> +         * \namespace rtype
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Server/Libs/AMonster.hpp
> +                 * \brief Get the Position object
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/GraphicalLib.hpp
> +            public:
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/GraphicalLib/IGraphicalLib.hpp
> +                virtual void print(size_t id) = 0; // for text
comment to delete

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/TCP/cTCPClient.hpp
> +                 *
wrong doc

2021-11-28 20:34 UTC, Jsavang commented on Sources/Client/Network/TCP/cTCPClient.hpp
> +                 * \param context asio context
wrong doc

2021-11-29 09:49 UTC, Jsavang approved these changes

2021-11-29 13:34 UTC, MaelTeyssedre approved these changes

2021-11-29 13:43 UTC, merged