Setup
MaelTeyssedre/R-TYPE pull request #80
Opened 2021-11-04 13:36 UTC by Jsavang

2021-11-04 13:40 UTC, Romain-GABET approved these changes
look good to me

2021-11-04 13:40 UTC, Romain-GABET commented on CMakeLists.txt
>  set(CONAN_DISABLE_CHECK_COMPILER TRUE CACHE INTERNAL "")
what is the purpose of this line?

2021-11-04 19:58 UTC, Jsavang commented
> look good to me

Thanks guy

2021-11-04 23:02 UTC, Alban-Bodenes commented on Setup.sh
> +mkdir build
Pense a check que le folder existe pas avant de le créer (Comme dans le script powershell)

2021-11-04 23:03 UTC, Alban-Bodenes approved these changes
LGTM

2021-11-06 16:01 UTC, MaelTeyssedre commented
changer le nom des scripts

2021-11-06 16:07 UTC, MaelTeyssedre requested changes
changer les nom des scripts

2021-11-07 22:29 UTC, MaelTeyssedre approved these changes

2021-11-07 22:30 UTC, merged